### ISSUE TITLE
How to compile it under OS X?

### ISSUE THREAD

**Issue by FleXoft** [blaztinn/submarine#4]
Need guide!

**Comment by reactormonk** [comment]
The only thing that really changes is where to get the libs: choose either macports or brew.

**Comment by silverkors** [comment]
I've tried, it doens't work for me. The libraries are all installed (thanks to brew and a formula for libsoup that isn't in the official repo yet).

I get the following error:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
configure.ac:7: warning: macro`AM_SILENT_RULES' not found in library
configure.ac:17: warning: macro `AM_PROG_VALAC' not found in library
configure.ac:1: error: Autoconf version 2.68 or higher is required
configure.ac:1: the top level
autom4te: /usr/bin/gm4 failed with exit status: 63
aclocal: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

I guess there is some problem with the path for the m4 files? They are in /usr/local/share/aclocal but I don't know how to make the autogen/configure stuff to understand that!

I am thankful for any help!

**Comment by reactormonk** [comment]
Looks like you need to update autoconf as well - the one provided by Apple seems to be ancient :-)

**Comment by FleXoft** [comment]
Here is my story:

--- CUT ---

macbookpro:development flex$ git clone https://github.com/blazt/submarine.git ; cd submarine ; ./autogen.sh ; ./configure ; make

Cloning into submarine...
remote: Counting objects: 159, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 159 (delta 84), reused 159 (delta 84)
Receiving objects: 100% (159/159), 67.32 KiB | 69 KiB/s, done.
Resolving deltas: 100% (84/84), done.
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: glibtoolize --copy
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR,`build-aux'.
glibtoolize: copying file `build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIR,`m4'.
glibtoolize: copying file `m4/libtool.m4'
glibtoolize: copying file`m4/ltoptions.m4'
glibtoolize: copying file `m4/ltsugar.m4'
glibtoolize: copying file`m4/ltversion.m4'
glibtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /opt/local/bin/autoconf
autoreconf: running: /opt/local/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:16: installing`build-aux/compile'
configure.ac:14: installing `build-aux/config.guess'
configure.ac:14: installing`build-aux/config.sub'
configure.ac:6: installing `build-aux/install-sh'
configure.ac:6: installing`build-aux/missing'
lib/Makefile.am: installing `build-aux/depcomp'
autoreconf: Leaving directory`.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking build system type... x86_64-apple-darwin11.2.0
checking host system type... x86_64-apple-darwin11.2.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld
checking if the linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm
checking the name lister (/usr/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-apple-darwin11.2.0 file names to x86_64-apple-darwin11.2.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin11.2.0 file names to toolchain format... func_convert_file_noop
checking for /usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/llvm-gcc-4.2/libexec/gcc/i686-apple-darwin11/4.2.1/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin11.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for valac... /opt/local/bin/valac
checking for pkg-config... /opt/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBSUBMARINE... yes
checking for SUBMARINE... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating lib/Makefile
config.status: creating submarine/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
Making all in lib
  VALAC  libsubmarine_la_vala.stamp
podnapisi.vala:132.47-132.63: warning: use of possibly unassigned parameter `format'
        private bool inflate_subtitle(uint8[] data, out string format, out string inflated_data) {
                                                    ^^^^^^^^^^^^^^^^^
podnapisi.vala:132.66-132.89: warning: use of possibly unassigned parameter`inflated_data'
        private bool inflate_subtitle(uint8[] data, out string format, out string inflated_data) {
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
Compilation succeeded - 2 warning(s)
  CC     libsubmarine_la-language_codes.lo
language_codes.c: In function 'submarine_get_language_info':
language_codes.c:351: warning: passing argument 6 of 'gee_hash_map_new' from incompatible pointer type
  CC     libsubmarine_la-subtitle.lo
  CC     libsubmarine_la-server.lo
server.c: In function 'submarine_subtitle_server_batch_process':
server.c:608: warning: passing argument 3 of 'gee_array_list_new' from incompatible pointer type
server.c:674: warning: passing argument 3 of 'gee_array_list_new' from incompatible pointer type
server.c: In function 'submarine_get_server_info':
server.c:1077: warning: passing argument 6 of 'gee_hash_map_new' from incompatible pointer type
  CC     libsubmarine_la-XMLRPC.lo
XMLRPC.c: In function 'submarine_xmlrpc_call':
XMLRPC.c:111: warning: assignment discards qualifiers from pointer target type
  CC     libsubmarine_la-open_subtitles.lo
open_subtitles.c: In function 'submarine_open_subtitles_server_language_codes_string':
open_subtitles.c:413: warning: assignment from incompatible pointer type
open_subtitles.c: In function 'submarine_open_subtitles_server_inflate_subtitle':
open_subtitles.c:634: error: 'GZlibDecompressor' undeclared (first use in this function)
open_subtitles.c:634: error: (Each undeclared identifier is reported only once
open_subtitles.c:634: error: for each function it appears in.)
open_subtitles.c:634: error: '_tmp4_' undeclared (first use in this function)
open_subtitles.c:635: error: '_tmp5_' undeclared (first use in this function)
open_subtitles.c:636: error: 'GConverterOutputStream' undeclared (first use in this function)
open_subtitles.c:636: error: '_tmp6_' undeclared (first use in this function)
open_subtitles.c:637: error: '_tmp7_' undeclared (first use in this function)
open_subtitles.c:638: error: 'conv_stream' undeclared (first use in this function)
open_subtitles.c:651: error: 'G_ZLIB_COMPRESSOR_FORMAT_GZIP' undeclared (first use in this function)
open_subtitles.c:653: error: expected expression before ')' token
open_subtitles.c: In function 'submarine_open_subtitles_server_real_search_multiple':
open_subtitles.c:1094: warning: passing argument 3 of 'gee_array_list_new' from incompatible pointer type
open_subtitles.c:1159: warning: format '%016llx' expects type 'long long unsigned int', but argument 2 has type 'guint64'
open_subtitles.c:1236: warning: assignment from incompatible pointer type
open_subtitles.c: In function 'submarine_open_subtitles_server_real_download_multiple':
open_subtitles.c:1564: warning: passing argument 3 of 'gee_array_list_new' from incompatible pointer type
open_subtitles.c:1630: warning: assignment from incompatible pointer type
make[2]: **\* [libsubmarine_la-open_subtitles.lo] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2
macbookpro:submarine flex$ 

--- CUT ---

**Comment by silverkors** [comment]
**Tass:** Thank you very much! You got me in the right direction, I had to update the autotools stuff by hand, not too hard. And I hade to install gobject by hand as well. Otherwise brew did the job for me. After changing the path to the new auto-stuff it all worked out for me!

Submarine works on my Mac (10.7) now! Wonderful!

**Comment by FleXoft** [comment]
"sudo port install glib2 libsoup" helped for me (but I already had these packages via fink...). 

It works for me too!!!

**Comment by orpiske** [comment]
For those using brew, I created a Tap overlay for it at https://github.com/orpiske/homebrew-alt

**Comment by silverkors** [comment]
**orpiske**: Thanks for that! I will save the link for future installations of submarine. It was a bit tedious doing it all by hand. :)
